method = "bayes"

[metric]
name = "val_loss_epoch"
goal = "minimize"

[parameters.batch_size]
values = [ 2, 4, 8, 16, 32, 64, 128, 256,]

[parameters.layer1]
values = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 32, 64, 128,]

[parameters.layer2]
values = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 16, 32, 64, 128,]

[parameters.lr]
values = [ 1e-5, 0.0001, 0.001, 0.01, 0.1, 1.0, 10.0,]
